### ISSUE TITLE
NVidia (Advanced) Optimus issue: SSB.exe forces dGPU in use

### ISSUE THREAD

**Issue by Hexaae** [jacob-pro/solar-screen-brightness#41]
Please, can you fix this?
SSB.exe when running locks dGPU=ON on a (Advanced) Optimus system. Obviously I can change screen brightness also in iGPU mode from Windows settings, and expected SSB.exe to work the same...

**Comment by jacob-pro** [comment]
Hmmm I think there is an API available to choose this in the graphics library this program is based on:
https://docs.rs/wgpu/0.20.1/wgpu/enum.PowerPreference.html
I will try and have a look when I have time. 
I would imagine it only uses the GPU when the window is open though so hopefully isn't very impactful?

**Comment by Hexaae** [comment]
Unfortunately even minimized in the tray dGPU is still locked

**Comment by jacob-pro** [comment]
This should be fixed in the latest version: https://github.com/jacob-pro/solar-screen-brightness/releases/tag/2.3.2

**Comment by Hexaae** [comment]
Confirmed!
This one is still reproducible with 2.3.2 though: https://github.com/jacob-pro/solar-screen-brightness/issues/43
